### ISSUE TITLE
Couldn’t get it to work with a Chromecast ultra

### ISSUE THREAD

**Issue by rimonhanna** [benov84/homebridge-chromecast-television#13]

**Comment by benov84** [comment]
which version you're using. if on 1.0.9, try update to 1.0.10. the plugin works with chromecast ultra, but there was an error with the previous version

**Comment by rimonhanna** [comment]
I'm using the latest version, what I noticed is that if I'm casting to the chromecast and I power it off using the home app, it pauses the stream rather than stopping it, is that intentional? Could it be that the ultra expects a different stop command?

**Comment by benov84** [comment]
The power off function in HomeKit pauses the stream. That is what it does now. I will try to make a config change, so you can specify the behavior- play/pause or nothing/off.
Nothing, because you cannot turn streaming on without specifying what to play :)

**Comment by rimonhanna** [comment]
Brilliant! Thanks!
