### ISSUE TITLE
Consider using on/off toggle to change TV power status?

### ISSUE THREAD

**Issue by anonymous-tech-user** [benov84/homebridge-chromecast-television#16]
Just a feature request that would be nice to have: Could it be possible to toggle the power status of the connected TV with the Chromecast using HDMI-CEC? The control center remote already has play/pause button and so being able to use the HomeKit power button to turn the TV on/off would be pretty handy.

**Comment by benov84** [comment]
I will check if it is possible :)

**Comment by Marfre888** [comment]
I second this, would really be a great feature..

Also, the ability to define a chromecast at a specific address, so it doesn't go to 'No Response' if power is turned off to it

**Comment by benov84** [comment]
Hi, in new version 2 switching on/off in home app now stops the stream. Volume control and play/pause are in remote in control center.

**Comment by benov84** [comment]
I will check the HDMI-CEC further...
