### ISSUE TITLE
No plugin was found…

### ISSUE THREAD

**Issue by angyalz** [benov84/homebridge-chromecast-television#2]
![image](https://user-images.githubusercontent.com/73586136/111887523-e2244800-89d5-11eb-95ed-8fab7bbb7d43.jpeg)

**Comment by angyalz** [comment]
homebridge.log content:

[39m[31m====================[39m
[37m[2021. 03. 20. 23:11:59] [39m[31mERROR LOADING PLUGIN homebridge-chromecast-television:[39m
[37m[2021. 03. 20. 23:11:59] [39m[31mError: Cannot find module 'hap-nodejs'[39m
[31mRequire stack:[39m
[31m- /usr/local/lib/node_modules/homebridge-chromecast-television/custom-characteristics.js[39m
[31m- /usr/local/lib/node_modules/homebridge-chromecast-television/index.js[39m
[31m- /usr/local/lib/node_modules/homebridge/lib/plugin.js[39m
[31m- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js[39m
[31m- /usr/local/lib/node_modules/homebridge/lib/server.js[39m
[31m- /usr/local/lib/node_modules/homebridge/lib/cli.js[39m
[31m- /usr/local/lib/node_modules/homebridge/bin/homebridge[39m
[31m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)[39m
[31m    at Function.Module._load (node:internal/modules/cjs/loader:769:27)[39m
[31m    at Module.require (node:internal/modules/cjs/loader:996:19)[39m
[31m    at require (node:internal/modules/cjs/helpers:92:18)[39m
[31m    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-chromecast-television/custom-characteristics.js:1:28)[39m
[31m    at Module._compile (node:internal/modules/cjs/loader:1092:14)[39m
[31m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)[39m
[31m    at Module.load (node:internal/modules/cjs/loader:972:32)[39m
[31m    at Function.Module._load (node:internal/modules/cjs/loader:813:14)[39m
[31m    at Module.require (node:internal/modules/cjs/loader:996:19)[39m
[37m[2021. 03. 20. 23:11:59] 


I think hap-nodejs is missing from package.json dependencies

**Comment by benov84** [comment]
Yes it is missing, I removed it but don't have to.
Please run this

Run the following command to install hap-nodejs manually and allow the plugin to run.
npm i -g hap-nodejs

I will fix this ASAP and will update the plug-in

**Comment by angyalz** [comment]
I added manually hap-nodejs to package.json dependencies and ran sudo npm i, I just failed to give feedback. It works for me.

**Comment by benov84** [comment]
Thanks for your help! I've fixed this and published updated version
