### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by gferreroferri** [benov84/homebridge-chromecast-television#20]
I have tried to install the plugin but I got the following error:

USER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-chromecast-television@latest

npm ERR! code 1
npm ERR! path /usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns/build'
npm ERR!   CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
npm ERR! make: Leaving directory '/usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.1 | linux | arm
npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/homebridge/.cache/node-gyp/16.13.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/homebridge/.cache/node-gyp/16.13.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/homebridge/.cache/node-gyp/16.13.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/dns_sd.cpp:1:
npm ERR! ../src/mdns.hpp:32:10: fatal error: dns_sd.h: No such file or directory
npm ERR!  #include <dns_sd.h>
npm ERR!           ^~~~~~~~~~
npm ERR! compilation terminated.
npm ERR! make: *** [dns_sd_bindings.target.mk:180: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.10.63-v7l+
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2022-01-12T07_34_37_295Z-debug.log

Command failed. Please review log for details.

**Comment by angyalz** [comment]
> I have tried to install the plugin but I got the following error:
> 
> USER: homebridge DIR: /usr CMD: sudo -E -n npm install -g homebridge-chromecast-television@latest
> 
> npm ERR! code 1 npm ERR! path /usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns npm ERR! command failed npm ERR! command sh -c node-gyp rebuild npm ERR! make: Entering directory '/usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns/build' npm ERR! CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o npm ERR! make: Leaving directory '/usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns/build' npm ERR! gyp info it worked if it ends with ok npm ERR! gyp info using node-gyp@8.3.0 npm ERR! gyp info using node@16.13.1 | linux | arm npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3" npm ERR! gyp info spawn /usr/bin/python3 npm ERR! gyp info spawn args [ npm ERR! gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py', npm ERR! gyp info spawn args 'binding.gyp', npm ERR! gyp info spawn args '-f', npm ERR! gyp info spawn args 'make', npm ERR! gyp info spawn args '-I', npm ERR! gyp info spawn args '/usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns/build/config.gypi', npm ERR! gyp info spawn args '-I', npm ERR! gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi', npm ERR! gyp info spawn args '-I', npm ERR! gyp info spawn args '/home/homebridge/.cache/node-gyp/16.13.1/include/node/common.gypi', npm ERR! gyp info spawn args '-Dlibrary=shared_library', npm ERR! gyp info spawn args '-Dvisibility=default', npm ERR! gyp info spawn args '-Dnode_root_dir=/home/homebridge/.cache/node-gyp/16.13.1', npm ERR! gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp', npm ERR! gyp info spawn args '-Dnode_lib_file=/home/homebridge/.cache/node-gyp/16.13.1/<(target_arch)/node.lib', npm ERR! gyp info spawn args '-Dmodule_root_dir=/usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns', npm ERR! gyp info spawn args '-Dnode_engine=v8', npm ERR! gyp info spawn args '--depth=.', npm ERR! gyp info spawn args '--no-parallel', npm ERR! gyp info spawn args '--generator-output', npm ERR! gyp info spawn args 'build', npm ERR! gyp info spawn args '-Goutput_dir=.' npm ERR! gyp info spawn args ] npm ERR! gyp info spawn make npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ] npm ERR! In file included from ../src/dns_sd.cpp:1: npm ERR! ../src/mdns.hpp:32:10: fatal error: dns_sd.h: No such file or directory npm ERR! #include <dns_sd.h> npm ERR! ^~~~~~~~~~ npm ERR! compilation terminated. npm ERR! make: *** [dns_sd_bindings.target.mk:180: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1 npm ERR! gyp ERR! build error npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2 npm ERR! gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23) npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:390:28) npm ERR! gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) npm ERR! gyp ERR! System Linux 5.10.63-v7l+ npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" npm ERR! gyp ERR! cwd /usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns npm ERR! gyp ERR! node -v v16.13.1 npm ERR! gyp ERR! node-gyp -v v8.3.0 npm ERR! gyp ERR! not ok
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /home/homebridge/.npm/_logs/2022-01-12T07_34_37_295Z-debug.log
> 
> Command failed. Please review log for details.

This package requires mdns npm package, but it needs libavahi-compat-libdnssd-dev package from your Linux repository. So please install it (sudo apt install libavahi-compat-libdnssd-dev), and try again to install this chromecast nom package to HomeBridge

**Comment by gferreroferri** [comment]
Thanks! Now it is installed, however I cannot see the accessory in Home app even after reconfiguring the Homebride on the app

**Comment by goldjunge91** [comment]
Hi I have different installition error
My setup is a radpberry pi with socker on that I’m running homebridge, and I’m not sure how the name of my chromecast is it’s have on my router the name Android and on google home app the name Tv.
Her my error log

`pointer.de/blog/projects/avahi-compat.html>
[6/16/2022, 1:38:52 AM] [Homebridge UI] Changes to config.json saved.
[6/16/2022, 1:38:52 AM] Loaded plugin: homebridge-chromecast-television@2.0.10
[6/16/2022, 1:38:52 AM] Registering platform 'homebridge-chromecast-television.ChromecastTelevision'
[6/16/2022, 1:38:52 AM] ---
[6/16/2022, 1:38:52 AM] Loaded plugin: homebridge-dummy@0.6.0
[6/16/2022, 1:38:52 AM] Registering accessory 'homebridge-dummy.DummySwitch'
[6/16/2022, 1:38:52 AM] ---
[6/16/2022, 1:38:52 AM] Loaded plugin: homebridge-tp-link-tapo@3.2.0
[6/16/2022, 1:38:52 AM] Registering platform 'homebridge-tp-link-tapo.HomebridgeTPLinkTapo'
[6/16/2022, 1:38:52 AM] ---
[6/16/2022, 1:38:52 AM] Loaded plugin: homebridge-config-ui-x@4.45.0
[6/16/2022, 1:38:52 AM] Registering platform 'homebridge-config-ui-x.config'
[6/16/2022, 1:38:52 AM] ---
[6/16/2022, 1:38:52 AM] Loading 3 platforms...
[6/16/2022, 1:38:52 AM] [Config] Initializing config platform...
[6/16/2022, 1:38:52 AM] [Config] Running in Service Mode
[6/16/2022, 1:38:52 AM] [tozzi9142] Initializing HomebridgeTPLinkTapo platform...
[6/16/2022, 1:38:52 AM] [Android-2] Initializing ChromecastTelevision platform...
[6/16/2022, 1:38:52 AM] Error: dns service error: unknown
    at new Browser (/homebridge/node_modules/homebridge-chromecast-television/node_modules/mdns/lib/browser.js:88:10)
    at Object.create [as createBrowser] (/homebridge/node_modules/homebridge-chromecast-television/node_modules/mdns/lib/browser.js:116:10)
    at new ControlChromecastPlatform (/homebridge/node_modules/homebridge-chromecast-television/index.js:47:29)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:442:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:161:29)
(node:1712) Warning: Accessing non-existent property 'Characteristic' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[6/16/2022, 1:38:52 AM] Got SIGTERM, shutting down Homebridge...
[6/16/2022, 1:38:57 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[6/16/2022, 1:39:02 AM] [HB Supervisor] Restarting Homebridge...
[6/16/2022, 1:39:02 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[6/16/2022, 1:39:02 AM] [HB Supervisor] Started Homebridge v1.4.1 with PID: 1737
[6/16/2022, 1:39:04 AM] Loaded config.json with 0 accessories and 3 platforms.
[6/16/2022, 1:39:04 AM] Loaded 1 cached accessories from cachedAccessories.
[6/16/2022, 1:39:04 AM] ---
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
[6/16/2022, 1:39:05 AM] Disabled plugin: homebridge-chromecast-television@2.0.10
[6/16/2022, 1:39:05 AM] ---
[6/16/2022, 1:39:05 AM] Loaded plugin: homebridge-dummy@0.6.0    `
>

**Comment by benov84** [comment]
This is related with installing mdns library, a prerequisite to this repository.

https://github.com/agnat/node_mdns

Try to install the library itself using the instructions and file an issue there, please.
