### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ghost** [benov84/homebridge-chromecast-television#21]
Trying to install on **Raspberry Pi 400 Rev1 4GB running on Twister OS 2.1**  - results in the below error (even after full reinstall of Homebridge) Can anybody help?

USER: homebridge
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-chromecast-television@2.0.10

(##################) ⠴ reify:protobufjs: timing reifyNode:node_modules/homebridge-chro
 \> mdns@2.7.2 install
\> node-gyp rebuild

make: Entering directory '/var/lib/homebridge/node_modules/homebridge-chromecast-television/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:
../src/mdns.hpp:32:10: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [dns_sd_bindings.target.mk:180: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/var/lib/homebridge/node_modules/homebridge-chromecast-television/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: \`make\` failed with exit code: 2
gyp ERR! stack(##################) ⠏ reify:protobufjs: timing reifyNode:node_modules/ho     at ChildProcess.onExit (/opt/homebridge/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.10.17-v7l+
gyp ERR! command "/opt/homebridge/bin/node" "/opt/homebridge/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/lib/homebridge/node_modules/homebridge-chromecast-television/node_modules/mdns
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /var/lib/homebridge/node_modules/homebridge-chromecast-television/node_modules/mdns
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2022-07-15T12_14_59_927Z-debug-0.log

Operation failed. Please review log for details.

**Comment by benov84** [comment]
This is related with installing mdns library, a prerequisite to this repository.

https://github.com/agnat/node_mdns

Try to install the library itself using the instructions and file an issue there, please.
