### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by hectorluisnavas** [benov84/homebridge-chromecast-television#22]
I have error when try to install this plugin in my Homebridge.

USER: homebridge
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-chromecast-television@2.0.10

(##################) ⠹ reify:@types/node: timing reifyNode:node_modules/homebridge-chr
> mdns@2.7.2 install
> node-gyp rebuild

make: se entra en el directorio '/var/lib/homebridge/node_modules/homebridge-chromecast-television/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:
../src/mdns.hpp:32:10: fatal error: dns_sd.h: No existe el fichero o el directorio
   32 | #include <dns_sd.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [dns_sd_bindings.target.mk:180: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: se sale del directorio '/var/lib/homebridge/node_modules/homebridge-chromecast-television/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/homebridge/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.15.61-v7l+
gyp ERR! command "/opt/homebridge/bin/node" "/opt/homebridge/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/lib/homebridge/node_modules/homebridge-chromecast-television/node_modules/mdns
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /var/lib/homebridge/node_modules/homebridge-chromecast-television/node_modules/mdns
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2022-09-17T20_16_46_572Z-debug-0.log

Operation failed. Please review log for details.

I attach my log file.

[2022-09-17T20_16_46_572Z-debug-0.log](https://github.com/benov84/homebridge-chromecast-television/files/9592588/2022-09-17T20_16_46_572Z-debug-0.log)

**Comment by lacha07** [comment]
Hello,
you can try to install missing dependency 
apt-get install libavahi-compat-libdnssd-dev
This solution come from https://stackoverflow.com/questions/19585117/error-dns-sd-h-no-such-file-or-directory

**Comment by hectorluisnavas** [comment]
the solution worked and I was able to install the plugin, homebridge and home kit app recognized Chromecast with Google TV; but unfortunately the only function that was enabled, which was the on/off switch, did not do anything on the device. I hope one day there will be a plugin that fully supports the new Chromecast Google TV. Thanks anyway for your help

**Comment by benov84** [comment]
This is related with installing mdns library, a prerequisite to this repository.

https://github.com/agnat/node_mdns

Try to install the library itself using the instructions and file an issue there, please.
