### ISSUE TITLE
instalation error

### ISSUE THREAD

**Issue by Jakes9** [benov84/homebridge-chromecast-television#23]
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   '-g',
0 verbose cli   'homebridge-chromecast-television@2.0.10'
0 verbose cli ]
1 info using npm@8.5.5
2 info using node@v16.15.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:C:\WINDOWS\system32\config\systemprofile\.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:C:\Users\jakub\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 10ms
18 timing npm:load:configload Completed in 10ms
19 timing npm:load:setTitle Completed in 0ms
20 timing config:load:flatten Completed in 3ms
21 timing npm:load:display Completed in 4ms
22 verbose logfile C:\WINDOWS\system32\config\systemprofile\AppData\Local\npm-cache\_logs\2022-09-22T10_30_43_050Z-debug-0.log
23 timing npm:load:logFile Completed in 6ms
24 timing npm:load:timers Completed in 0ms
25 timing npm:load:configScope Completed in 0ms
26 timing npm:load Completed in 21ms
27 timing arborist:ctor Completed in 0ms
28 silly logfile start cleaning logs, removing 2 files
29 timing idealTree:init Completed in 4ms
30 timing idealTree:userRequests Completed in 3ms
31 silly idealTree buildDeps
32 silly fetch manifest homebridge-chromecast-television@2.0.10
33 http fetch GET 200 https://registry.npmjs.org/homebridge-chromecast-television 824ms (cache revalidated)
34 silly placeDep ROOT homebridge-chromecast-television@2.0.10 OK for:  want: 2.0.10
35 silly fetch manifest castv2-client@^1.2.0
36 silly fetch manifest mdns@^2.3.3
37 http fetch GET 200 https://registry.npmjs.org/castv2-client 37ms (cache revalidated)
38 http fetch GET 200 https://registry.npmjs.org/mdns 255ms (cache revalidated)
39 timing idealTree:#root Completed in 1089ms
40 silly placeDep node_modules/homebridge-chromecast-television castv2-client@1.2.0 OK for: homebridge-chromecast-television@2.0.10 want: ^1.2.0
41 silly placeDep node_modules/homebridge-chromecast-television mdns@2.7.2 OK for: homebridge-chromecast-television@2.0.10 want: ^2.3.3
42 silly fetch manifest castv2@~0.1.4
43 silly fetch manifest debug@^2.2.0
44 silly fetch manifest bindings@~1.2.1
45 silly fetch manifest nan@^2.14.0
46 http fetch GET 200 https://registry.npmjs.org/debug 36ms (cache revalidated)
47 http fetch GET 200 https://registry.npmjs.org/nan 42ms (cache revalidated)
48 http fetch GET 200 https://registry.npmjs.org/bindings 63ms (cache revalidated)
49 http fetch GET 200 https://registry.npmjs.org/castv2 65ms (cache revalidated)
50 timing idealTree:node_modules/homebridge-chromecast-television Completed in 70ms
51 silly placeDep node_modules/homebridge-chromecast-television castv2@0.1.10 OK for: castv2-client@1.2.0 want: ~0.1.4
52 silly placeDep node_modules/homebridge-chromecast-television debug@2.6.9 OK for: castv2-client@1.2.0 want: ^2.2.0
53 silly fetch manifest debug@^4.1.1
54 silly fetch manifest protobufjs@^6.8.8
55 silly fetch manifest ms@2.0.0
56 http fetch GET 200 https://registry.npmjs.org/ms 36ms (cache revalidated)
57 http fetch GET 200 https://registry.npmjs.org/protobufjs 40ms (cache revalidated)
58 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/castv2-client Completed in 46ms
59 silly placeDep node_modules/homebridge-chromecast-television/node_modules/castv2 debug@4.3.4 OK for: castv2@0.1.10 want: ^4.1.1
60 silly placeDep node_modules/homebridge-chromecast-television protobufjs@6.11.3 OK for: castv2@0.1.10 want: ^6.8.8
61 silly fetch manifest ms@2.1.2
62 silly fetch manifest @protobufjs/aspromise@^1.1.2
63 silly fetch manifest @protobufjs/base64@^1.1.2
64 silly fetch manifest @protobufjs/codegen@^2.0.4
65 silly fetch manifest @protobufjs/eventemitter@^1.1.0
66 silly fetch manifest @protobufjs/fetch@^1.1.0
67 silly fetch manifest @protobufjs/float@^1.0.2
68 silly fetch manifest @protobufjs/inquire@^1.1.0
69 silly fetch manifest @protobufjs/path@^1.1.2
70 silly fetch manifest @protobufjs/pool@^1.1.0
71 silly fetch manifest @protobufjs/utf8@^1.1.0
72 silly fetch manifest @types/long@^4.0.1
73 silly fetch manifest @types/node@>=13.7.0
74 silly fetch manifest long@^4.0.0
75 http fetch GET 200 https://registry.npmjs.org/@protobufjs%2faspromise 70ms (cache revalidated)
76 http fetch GET 200 https://registry.npmjs.org/@protobufjs%2fbase64 69ms (cache revalidated)
77 http fetch GET 200 https://registry.npmjs.org/@protobufjs%2fcodegen 78ms (cache revalidated)
78 http fetch GET 200 https://registry.npmjs.org/long 76ms (cache revalidated)
79 http fetch GET 200 https://registry.npmjs.org/@protobufjs%2feventemitter 82ms (cache revalidated)
80 http fetch GET 200 https://registry.npmjs.org/@types%2flong 84ms (cache revalidated)
81 http fetch GET 200 https://registry.npmjs.org/@types%2fnode 88ms (cache revalidated)
82 http fetch GET 200 https://registry.npmjs.org/@protobufjs%2futf8 99ms (cache revalidated)
83 http fetch GET 200 https://registry.npmjs.org/@protobufjs%2ffetch 101ms (cache revalidated)
84 http fetch GET 200 https://registry.npmjs.org/@protobufjs%2fpool 100ms (cache revalidated)
85 http fetch GET 200 https://registry.npmjs.org/@protobufjs%2ffloat 101ms (cache revalidated)
86 http fetch GET 200 https://registry.npmjs.org/@protobufjs%2finquire 107ms (cache revalidated)
87 http fetch GET 200 https://registry.npmjs.org/@protobufjs%2fpath 136ms (cache revalidated)
88 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/castv2 Completed in 142ms
89 silly placeDep node_modules/homebridge-chromecast-television ms@2.0.0 OK for: debug@2.6.9 want: 2.0.0
90 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/debug Completed in 1ms
91 silly placeDep node_modules/homebridge-chromecast-television bindings@1.2.1 OK for: mdns@2.7.2 want: ~1.2.1
92 silly placeDep node_modules/homebridge-chromecast-television nan@2.16.0 OK for: mdns@2.7.2 want: ^2.14.0
93 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/mdns Completed in 3ms
94 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/bindings Completed in 0ms
95 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/ms Completed in 0ms
96 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/nan Completed in 0ms
97 silly placeDep node_modules/homebridge-chromecast-television @protobufjs/aspromise@1.1.2 OK for: protobufjs@6.11.3 want: ^1.1.2
98 silly placeDep node_modules/homebridge-chromecast-television @protobufjs/base64@1.1.2 OK for: protobufjs@6.11.3 want: ^1.1.2
99 silly placeDep node_modules/homebridge-chromecast-television @protobufjs/codegen@2.0.4 OK for: protobufjs@6.11.3 want: ^2.0.4
100 silly placeDep node_modules/homebridge-chromecast-television @protobufjs/eventemitter@1.1.0 OK for: protobufjs@6.11.3 want: ^1.1.0
101 silly placeDep node_modules/homebridge-chromecast-television @protobufjs/fetch@1.1.0 OK for: protobufjs@6.11.3 want: ^1.1.0
102 silly placeDep node_modules/homebridge-chromecast-television @protobufjs/float@1.0.2 OK for: protobufjs@6.11.3 want: ^1.0.2
103 silly placeDep node_modules/homebridge-chromecast-television @protobufjs/inquire@1.1.0 OK for: protobufjs@6.11.3 want: ^1.1.0
104 silly placeDep node_modules/homebridge-chromecast-television @protobufjs/path@1.1.2 OK for: protobufjs@6.11.3 want: ^1.1.2
105 silly placeDep node_modules/homebridge-chromecast-television @protobufjs/pool@1.1.0 OK for: protobufjs@6.11.3 want: ^1.1.0
106 silly placeDep node_modules/homebridge-chromecast-television @protobufjs/utf8@1.1.0 OK for: protobufjs@6.11.3 want: ^1.1.0
107 silly placeDep node_modules/homebridge-chromecast-television @types/long@4.0.2 OK for: protobufjs@6.11.3 want: ^4.0.1
108 silly placeDep node_modules/homebridge-chromecast-television @types/node@18.7.18 OK for: protobufjs@6.11.3 want: >=13.7.0
109 silly placeDep node_modules/homebridge-chromecast-television long@4.0.0 OK for: protobufjs@6.11.3 want: ^4.0.0
110 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/protobufjs Completed in 13ms
111 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/aspromise Completed in 0ms
112 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/base64 Completed in 1ms
113 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/codegen Completed in 0ms
114 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/eventemitter Completed in 0ms
115 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/fetch Completed in 0ms
116 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/float Completed in 0ms
117 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/inquire Completed in 0ms
118 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/path Completed in 0ms
119 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/pool Completed in 0ms
120 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/utf8 Completed in 0ms
121 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/@types/long Completed in 0ms
122 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/@types/node Completed in 0ms
123 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/long Completed in 0ms
124 silly placeDep node_modules/homebridge-chromecast-television/node_modules/castv2 ms@2.1.2 OK for: debug@4.3.4 want: 2.1.2
125 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/castv2/node_modules/debug Completed in 1ms
126 timing idealTree:node_modules/homebridge-chromecast-television/node_modules/castv2/node_modules/ms Completed in 0ms
127 timing idealTree:buildDeps Completed in 1369ms
128 timing idealTree:fixDepFlags Completed in 1ms
129 timing idealTree Completed in 1378ms
130 timing reify:loadTrees Completed in 1380ms
131 timing reify:diffTrees Completed in 1ms
132 silly reify moves {}
133 timing reify:retireShallow Completed in 0ms
134 timing reify:createSparse Completed in 6ms
135 timing reify:loadBundles Completed in 0ms
136 silly audit bulk request {
136 silly audit   'homebridge-chromecast-television': [ '2.0.10' ],
136 silly audit   'castv2-client': [ '1.2.0' ],
136 silly audit   mdns: [ '2.7.2' ],
136 silly audit   castv2: [ '0.1.10' ],
136 silly audit   debug: [ '2.6.9', '4.3.4' ],
136 silly audit   protobufjs: [ '6.11.3' ],
136 silly audit   ms: [ '2.0.0', '2.1.2' ],
136 silly audit   bindings: [ '1.2.1' ],
136 silly audit   nan: [ '2.16.0' ],
136 silly audit   '@protobufjs/aspromise': [ '1.1.2' ],
136 silly audit   '@protobufjs/base64': [ '1.1.2' ],
136 silly audit   '@protobufjs/codegen': [ '2.0.4' ],
136 silly audit   '@protobufjs/eventemitter': [ '1.1.0' ],
136 silly audit   '@protobufjs/fetch': [ '1.1.0' ],
136 silly audit   '@protobufjs/float': [ '1.0.2' ],
136 silly audit   '@protobufjs/inquire': [ '1.1.0' ],
136 silly audit   '@protobufjs/path': [ '1.1.2' ],
136 silly audit   '@protobufjs/pool': [ '1.1.0' ],
136 silly audit   '@protobufjs/utf8': [ '1.1.0' ],
136 silly audit   '@types/long': [ '4.0.2' ],
136 silly audit   '@types/node': [ '18.7.18' ],
136 silly audit   long: [ '4.0.0' ]
136 silly audit }
137 http fetch GET 200 https://registry.npmjs.org/homebridge-chromecast-television/-/homebridge-chromecast-television-2.0.10.tgz 145ms (cache revalidated)
138 http fetch GET 200 https://registry.npmjs.org/long/-/long-4.0.0.tgz 148ms (cache revalidated)
139 http fetch GET 200 https://registry.npmjs.org/@types/long/-/long-4.0.2.tgz 145ms (cache revalidated)
140 http fetch GET 200 https://registry.npmjs.org/@protobufjs/pool/-/pool-1.1.0.tgz 156ms (cache revalidated)
141 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/@types/long Completed in 194ms
142 http fetch GET 200 https://registry.npmjs.org/@types/node/-/node-18.7.18.tgz 192ms (cache revalidated)
143 http fetch GET 200 https://registry.npmjs.org/@protobufjs/base64/-/base64-1.1.2.tgz 163ms (cache revalidated)
144 http fetch GET 200 https://registry.npmjs.org/@protobufjs/aspromise/-/aspromise-1.1.2.tgz 163ms (cache revalidated)
145 http fetch GET 200 https://registry.npmjs.org/ms/-/ms-2.0.0.tgz 164ms (cache revalidated)
146 http fetch GET 200 https://registry.npmjs.org/@protobufjs/eventemitter/-/eventemitter-1.1.0.tgz 186ms (cache revalidated)
147 http fetch GET 200 https://registry.npmjs.org/ms/-/ms-2.1.2.tgz 165ms (cache revalidated)
148 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 238ms
149 timing auditReport:getReport Completed in 239ms
150 silly audit report {}
151 timing auditReport:init Completed in 0ms
152 timing reify:audit Completed in 241ms
153 timing reifyNode:node_modules/homebridge-chromecast-television Completed in 242ms
154 http fetch GET 200 https://registry.npmjs.org/@protobufjs/fetch/-/fetch-1.1.0.tgz 196ms (cache revalidated)
155 http fetch GET 200 https://registry.npmjs.org/nan/-/nan-2.16.0.tgz 191ms (cache revalidated)
156 http fetch GET 200 https://registry.npmjs.org/debug/-/debug-4.3.4.tgz 181ms (cache revalidated)
157 http fetch GET 200 https://registry.npmjs.org/@protobufjs/path/-/path-1.1.2.tgz 236ms (cache revalidated)
158 http fetch GET 200 https://registry.npmjs.org/@protobufjs/float/-/float-1.0.2.tgz 235ms (cache revalidated)
159 http fetch GET 200 https://registry.npmjs.org/@protobufjs/inquire/-/inquire-1.1.0.tgz 235ms (cache revalidated)
160 http fetch GET 200 https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz 209ms (cache revalidated)
161 http fetch GET 200 https://registry.npmjs.org/castv2/-/castv2-0.1.10.tgz 196ms (cache revalidated)
162 http fetch GET 200 https://registry.npmjs.org/mdns/-/mdns-2.7.2.tgz 206ms (cache revalidated)
163 http fetch GET 200 https://registry.npmjs.org/@protobufjs/codegen/-/codegen-2.0.4.tgz 237ms (cache revalidated)
164 http fetch GET 200 https://registry.npmjs.org/debug/-/debug-2.6.9.tgz 216ms (cache revalidated)
165 http fetch GET 200 https://registry.npmjs.org/protobufjs/-/protobufjs-6.11.3.tgz 238ms (cache revalidated)
166 http fetch GET 200 https://registry.npmjs.org/@protobufjs/utf8/-/utf8-1.1.0.tgz 290ms (cache revalidated)
167 http fetch GET 200 https://registry.npmjs.org/castv2-client/-/castv2-client-1.2.0.tgz 235ms (cache revalidated)
168 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/ms Completed in 329ms
169 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/pool Completed in 330ms
170 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/castv2/node_modules/ms Completed in 330ms
171 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/long Completed in 334ms
172 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/bindings Completed in 334ms
173 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/base64 Completed in 341ms
174 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/aspromise Completed in 342ms
175 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/eventemitter Completed in 343ms
176 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/fetch Completed in 345ms
177 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/path Completed in 346ms
178 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/codegen Completed in 347ms
179 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/castv2/node_modules/debug Completed in 347ms
180 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/float Completed in 352ms
181 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/utf8 Completed in 353ms
182 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/@protobufjs/inquire Completed in 355ms
183 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/castv2 Completed in 361ms
184 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/debug Completed in 363ms
185 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/castv2-client Completed in 364ms
186 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/nan Completed in 393ms
187 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/mdns Completed in 409ms
188 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/@types/node Completed in 423ms
189 timing reifyNode:node_modules/homebridge-chromecast-television/node_modules/protobufjs Completed in 499ms
190 timing reify:unpack Completed in 500ms
191 timing reify:unretire Completed in 0ms
192 timing build:queue Completed in 2ms
193 timing build:link:node_modules/homebridge-chromecast-television/node_modules/protobufjs Completed in 6ms
194 timing build:link Completed in 6ms
195 info run mdns@2.7.2 install node_modules/homebridge-chromecast-television/node_modules/mdns node-gyp rebuild
196 info run mdns@2.7.2 install { code: 1, signal: null }
197 timing reify:rollback:createSparse Completed in 66ms
198 timing reify:rollback:retireShallow Completed in 0ms
199 timing command:install Completed in 2220ms
200 verbose stack Error: command failed
200 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
200 verbose stack     at ChildProcess.emit (node:events:527:28)
200 verbose stack     at maybeClose (node:internal/child_process:1092:16)
200 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
201 verbose pkgid mdns@2.7.2
202 verbose cwd C:\Users\jakub\AppData\Roaming\npm
203 verbose Windows_NT 10.0.22000
204 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "homebridge-chromecast-television@2.0.10"
205 verbose node v16.15.0
206 verbose npm  v8.5.5
207 error code 1
208 error path C:\Users\jakub\AppData\Roaming\npm\node_modules\homebridge-chromecast-television\node_modules\mdns
209 error command failed
210 error command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
211 verbose exit 1
212 timing npm Completed in 2518ms
213 verbose unfinished npm timer reify 1663842643345
214 verbose unfinished npm timer reify:build 1663842645247
215 verbose unfinished npm timer build 1663842645247
216 verbose unfinished npm timer build:deps 1663842645248
217 verbose unfinished npm timer build:run:install 1663842645256
218 verbose unfinished npm timer build:run:install:node_modules/homebridge-chromecast-television/node_modules/mdns 1663842645257
219 verbose code 1
220 error A complete log of this run can be found in:
220 error     C:\WINDOWS\system32\config\systemprofile\AppData\Local\npm-cache\_logs\2022-09-22T10_30_43_050Z-debug-0.log

**Comment by Jakes9** [comment]
I dont know how to install this plugin

**Comment by benov84** [comment]
This is related with installing mdns library, a prerequisite to this repository.

https://github.com/agnat/node_mdns

Try to install the library itself using the instructions and file an issue there, please.
