### ISSUE TITLE
No volume option on Remote TV App

### ISSUE THREAD

**Issue by caldera098** [benov84/homebridge-chromecast-television#25]
Hello there,

Plugin is working properly and the Remote TV App detects the chromecast. Even play/pause works fine, but no volume option. The only options that appear ar arrow up/down/left/right, select, back and info; all of them don't work and kinda lags homebridge for a couple of seconds. The following warning shows up in terminal:

> [5/4/2023, 12:19:23 AM] [ChromecastTelevision] set Remote Key Pressed: ARROW_UP
> [5/4/2023, 12:19:32 AM] [homebridge-chromecast-television] This plugin slows down Homebridge. The write handler for the characteristic 'Remote Key' on the accessory 'Chromecast-1d542550c06cabae21815c98965945d7 EA75' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.

I don't really care about this, but what I found most interesting about this plugin is the volume control. 
I'll be glad if someone can help. By the way I'm using Homebridge on Docker (Windows Hyper-V).

Thanks!!

**Comment by benov84** [comment]
Hi, you can control the volume with hardware buttons on your iPhone when in Remove TV app.
