### ISSUE TITLE
Is it working for anyone?

### ISSUE THREAD

**Issue by Varrial** [benov84/homebridge-chromecast-television#27]
### Hi, I install the app on homebridge. 
![Zrzut ekranu 2023-10-15 o 23 09 14](https://github.com/benov84/homebridge-chromecast-television/assets/73936910/451f7e72-4139-48fd-9d43-f9d4e8855ab0)

### After restart I see TV's in accessories 
![Zrzut ekranu 2023-10-15 o 23 18 22](https://github.com/benov84/homebridge-chromecast-television/assets/73936910/52345fdf-fd23-4ab7-b6df-82f169f4a6c7)

### but despite restarting and adding bridge to HomeApp
![IMG_8938](https://github.com/benov84/homebridge-chromecast-television/assets/73936910/666dc302-42dd-4b83-baea-c5ff5cf23330)

### there is no new devices on my App, also in remote TV app there is no way to control or even find tv. 
![IMG_8939](https://github.com/benov84/homebridge-chromecast-television/assets/73936910/434d1e7d-c4cd-4d0d-8ea5-e6483e0f5244)

**Comment by benov84** [comment]
The TV accessories must be added separately from bridge to Home app.

**Comment by Varrial** [comment]
thanks for fast response, can you tell me how to do this?

**Comment by benov84** [comment]
[Go to add new accessory, ](https://9to5mac.com/2020/05/19/manually-add-homekit-accessory-home-app-iphone-ipad/)
See here. It is a little bit outdated, but the process is the same.
When asked for setup code , enter the same code as your homebridge.
