### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by anonymous-tech-user** [benov84/homebridge-chromecast-television#7]
I'm getting the following error and can't make much sense of it when installing the plugin:

`> mdns@2.7.2 install /usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:10: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
          ^~~~~~~~~~
compilation terminated.
dns_sd_bindings.target.mk:180: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.15.0-136-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-chromecast-television/node_modules/mdns
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2021-06-15T15_13_27_648Z-debug.log

Command failed. Please review log for details.
`

**Comment by benov84** [comment]
Please reade this:
https://www.npmjs.com/package/mdns

Because this library requires mdns, you should install the dependencies of mdns for your OS from above link.

**Comment by benov84** [comment]
closed
