### ISSUE TITLE
Does Volume Work?

### ISSUE THREAD

**Issue by rcoletti116** [benov84/homebridge-chromecast-television#9]
I can play/pause with the On/Off, but using the remote to control volume (per readme) doesn't do anything. I have a regular Chromecast. There are no corresponding logs. I'm curious if this is known working and for which device versions?

**Comment by benov84** [comment]
This works with my first generation chromecast. I don't have other devices to test.

**Comment by rcoletti116** [comment]
I have a 1st gen as well. Does it matter which type of device you set it up as? Streaming Stick vs Television, etc...?

**Comment by benov84** [comment]
I don't think so, but I'm using mine as television.
I will try to put some logs so you can investigate.
